### ISSUE TITLE
json request from Layer fails when "IF" statement in MG_TOOLTIP

### ISSUE THREAD

**Issue by mapguideguy** [jumpinjackie/mapguide-rest#116]
Error using the feature.properties.MG_TOOLTIP in the layer GEOJSON, if there is an IF statement for example:

IF('NOT RPROPAD = ''',CONCAT ('label: ',  RPROPAD ),'No Label')

Works great in Tooltip in MapGuide, but returns error if requested with JSON in mapguide-rest.

http://localhost/mapguide/rest/library/Samples/Sheboygan/Layers/Parcels.LayerDefinition/features.geojson

 Item 'IF' not found in collection  (Cause: , Root Cause: Item 'IF' not found in collection )", "Details": "An exception occurred in FDO component.\nError occurred in Feature Source (Library:\/\/Samples\/Sheboygan\/Data\/Parcels.FeatureSource): Item 'IF' not found in collection

**Comment by jumpinjackie** [comment]
Is this expression even valid? I seem to always get the tooltip to show "No Label", even when hovering over parcels with an actual RPROPAD value.

**Comment by mapguideguy** [comment]
Yes, or you can try:
IF('NOT RPROPAD = ''''',CONCAT ('label: ', RPROPAD ),'No Label')
Count 5 single quotes after the equal sign..
              
              
still gives the error...
http://localhost/mapguide/rest/library/Samples/Sheboygan/Layers/Parcels.LayerDefinition/features.geojson Item 'IF' not found in collection  (Cause: , Root Cause: Item 'IF' not found in collection )

Date: Tue, 17 Nov 2015 06:30:05 -0800

**Comment by jumpinjackie** [comment]
I get it now.

IF (along with LOOKUP and RANGE) is a FDO expression function that is only recognized at rendering/stylization time. Adding it as a computed property in a standard query causes the error because such a function is not recognized by MapGuide or FDO at that particular point in time. I am guessing at this point in time, MapGuide/FDO is trying to parse it as an aliasing expression, hence that ("IF" not found in collection) error message.

There's nothing I can do about this at the mapguide-rest level. Such functions are plainly not supported for standard querying.
